name: Deploy to Vercel

on:
  push:
    branches:
      - main

env:
  NODE_ENV: production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Build the app
      run: npm run build

    - name: Deploy to Vercel
      uses: vercel/actions/cli@v2
      with:
        args: deploy
      env:
        NOW_TOKEN: ${{ secrets.VERCEL_TOKEN }}
